#!/usr/bin/env python3

import sys
from chat.GroupMe import *

def main(argv):
    '''
    assume just groupme chat for now
    '''
    chat = GroupMe()
    chat.run()


if __name__ == "__main__":
    main(sys.argv)
